coverage:
  round: down
  range: 60...90
  precision: 2
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 60%

ignore:
  - 'api_server/db'
  - 'api_server/generated'
  - 'api_server/models'
  - 'api_server/openapi'
  - 'api_server/test'
